#! /bin/bash

set -e

if test x"$1" = x--ci; then
    commits=.git.$(git rev-list --count HEAD)
    sed -i 's|\(AC_INIT(\[helpers\], \[\)\([^]]\+\)\(.*\)|\1\2'"$commits"'\3|' configure.ac
fi

gitdir=$(dirname "$0")
cd "$gitdir"

for i in bin libexec share/eimg etc/eimg
do
    target="$i" build-aux/gen-makefile-am > "$i/Makefile.inc"
done

autoreconf -vfi
./configure "--prefix=$(pwd)"
make
