#! /bin/bash

# Helper script (used by praiskup atm) to update CI scripting on Copr side.

script=$(readlink -f "$(dirname "$0")")/copr-custom-script
script_resultdir=resultdir
pkgname=praiskup-helpers

PROJECT_PR=praiskup/helpers-ci
PROJECT_PUSH=praiskup/helpers

build_deps=(
    automake
    git
    make
    python-unversioned-command
)

for PROJECT in $PROJECT_PR $PROJECT_PUSH; do
    copr_cmd=(
        copr edit-package-custom "$PROJECT" \
            --webhook-rebuild on \
            --script "$script" \
            --script-chroot "fedora-latest-x86_64" \
            --script-builddeps "${build_deps[*]}" \
            --name "$pkgname" \
            --script-resultdir "$script_resultdir"
    )
    test "$PROJECT" = "$PROJECT_PR" && copr_cmd+=( --max-builds 20 )
    "${copr_cmd[@]}"
done
