#! /bin/bash

# Generate Makefile.inc.
# Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

: ${target=.}

files=
files_in=

bin_SCRIPTS=
libexec_SCRIPTS=
eimgdata_DATA=
sysconf_DATA=
scripts=

echo '/.gitignore' > "$target/.gitignore"

while read dir primary file
do
    files+="$file
"
    files_in+=" %D%/$file.in"

    echo "$file" >> "$target/.gitignore"
    case $primary in
        SCRIPTS)
            eval "${dir}_$primary+=' %D%/$file '"
            scripts+=" %D%/$file "
            ;;
        DATA)
            eval "${dir}_DATA+=' %D%/$file '"
            data+=" %D%/$file "
            ;;
    esac
done < <(grep -v '^#' < "$target/Makefile.inc.in")

echo "bin_SCRIPTS += $bin_SCRIPTS"
echo "libexec_SCRIPTS += $libexec_SCRIPTS"
echo "eimgdata_DATA += $eimgdata_DATA "
echo "sysconf_DATA += $sysconf_DATA"

clean_files=
for t in data script
do
    var=$data
    action='$(text_tpl_gen)'
    case $t in
        data)
            ;;
        script)
            var=$scripts
            action='$(text_tpl_gen_script)'
            ;;
    esac

    for i in $var
    do
        echo "$i: \$(srcdir)/$i.in \$(c_s)"
        echo "	$action"

        clean_files+=" $i"
    done
done

echo "CLEANFILES += $clean_files"
echo "EXTRA_DIST += $files_in %D%/Makefile.inc.in"
